# Docs here for this file:
# https://github.com/wei/pull#readme

version: "1"
rules:
  - base: develop
    upstream: NYPL-Simplified:develop
    mergeMethod: none   # don't automatically merge, let us manually review first
