from flask_babel import lazy_gettext as _

# DO NOT EDIT THIS FILE MANUALLY!
# This file was generated by the CollectTranslationsScript class.

lanes = {
    "All Books": _("All Books"),
    "All Books in Other Languages": _("All Books in Other Languages"),
    "Books for Adults": _("Books for Adults"),
    "Books for Children": _("Books for Children"),
    "Books for Young Adults": _("Books for Young Adults"),
    "Books in Other Languages": _("Books in Other Languages"),
}
