version: "3.9"
services:
  # example docker compose configuration for testing and development

  webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: webapp
    ports:
      - "6500:80"
    environment:
      - TZ=Europe/Helsinki
      SIMPLIFIED_PRODUCTION_DATABASE: "postgresql://palace:test@pg:5432/circ"

  scripts:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: scripts
    environment:
      - TZ=Europe/Helsinki
      SIMPLIFIED_PRODUCTION_DATABASE: "postgresql://palace:test@pg:5432/circ"

  pg:
    image: "postgres:12"
    environment:
      - TZ=Europe/Helsinki
      POSTGRES_USER: palace
      POSTGRES_PASSWORD: test
      POSTGRES_DB: circ

  minio:
    image: "bitnami/minio:2023.2.27"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - TZ=Europe/Helsinki
      MINIO_ROOT_USER: "palace"
      MINIO_ROOT_PASSWORD: "test123456789"
      MINIO_SCHEME: "http"

  os:
    build:
      dockerfile: docker/Dockerfile.ci
      target: opensearch
    environment:
      - TZ=Europe/Helsinki
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: true
