"""Create Accessibility table

Revision ID: 786c0a715d1d
Revises: 5dce41f52b98
Create Date: 2025-09-26 10:59:00.564482+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "786c0a715d1d"
down_revision = "5dce41f52b98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accessibility",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Unicode(), nullable=True),
        sa.Column("ways_of_reading", postgresql.ARRAY(sa.Unicode()), nullable=True),
        sa.Column(
            "additional_accessibility_information",
            postgresql.ARRAY(sa.Unicode()),
            nullable=True,
        ),
        sa.Column("navigation", postgresql.ARRAY(sa.Unicode()), nullable=True),
        sa.Column("rich_content", postgresql.ARRAY(sa.Unicode()), nullable=True),
        sa.Column("hazards", postgresql.ARRAY(sa.Unicode()), nullable=True),
        sa.Column("conforms_to", postgresql.ARRAY(sa.Unicode()), nullable=True),
        sa.Column("certifier", sa.Unicode(), nullable=True),
        sa.Column("legal_considerations", sa.Unicode(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "editions", sa.Column("accessibility_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_editions_accessibility_id",
        "editions",
        "accessibility",
        ["accessibility_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_editions_accessibility_id", "editions", type_="foreignkey")
    op.drop_column("editions", "accessibility_id")
    op.drop_table("accessibility")
    # ### end Alembic commands ###
