"""is_missing and last_checked to License

Revision ID: 5dce41f52b98
Revises: d3aaeb6a9e6b
Create Date: 2025-03-21 12:06:18.992171+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5dce41f52b98"
down_revision = "d3aaeb6a9e6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "licenses", sa.Column("last_checked", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("licenses", sa.Column("is_missing", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("licenses", "is_missing")
    op.drop_column("licenses", "last_checked")
    # ### end Alembic commands ###
