"""fix defaults for is_missing

Revision ID: 377b096c0324
Revises: 4a14dc789118
Create Date: 2025-03-19 08:12:06.062590+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "377b096c0324"
down_revision = "4a14dc789118"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    licenses_table = sa.table("licenses", sa.column("is_missing"))
    op.execute(licenses_table.update().values(is_missing=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
