"""Remove patron _last_loan_activity_sync

Revision ID: 7d3add9fd1fe
Revises: 786c0a715d1d
Create Date: 2025-10-23 07:37:34.570783+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7d3add9fd1fe"
down_revision = "786c0a715d1d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patrons", "last_loan_activity_sync")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patrons",
        sa.Column(
            "last_loan_activity_sync",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
