from flask_babel import lazy_gettext as _

# DO NOT EDIT THIS FILE MANUALLY!
# This file was generated by the CollectTranslationsScript class.

w3c_display_texts = {
    "This publication meets minimum accessibility standards": _(
        "This publication meets minimum accessibility standards"
    ),
    "This publication meets accepted accessibility standards": _(
        "This publication meets accepted accessibility standards"
    ),
    "This publication exceeds accepted accessibility standards": _(
        "This publication exceeds accepted accessibility standards"
    ),
    "Flashing content": _("Flashing content"),
    "Motion simulation": _("Motion simulation"),
    "No information is available": _("No information is available"),
    "No hazards": _("No hazards"),
    "Sounds": _("Sounds"),
    "The presence of hazards is unknown": _("The presence of hazards is unknown"),
    "Has alternative text": _("Has alternative text"),
    "No information about nonvisual reading is available": _(
        "No information about nonvisual reading is available"
    ),
    "Not readable in read aloud or dynamic braille": _(
        "Not readable in read aloud or dynamic braille"
    ),
    "Not fully readable in read aloud or dynamic braille": _(
        "Not fully readable in read aloud or dynamic braille"
    ),
    "Readable in read aloud or dynamic braille": _(
        "Readable in read aloud or dynamic braille"
    ),
    "Prerecorded audio clips": _("Prerecorded audio clips"),
    "Prerecorded audio only": _("Prerecorded audio only"),
    "Prerecorded audio synchronized with text": _(
        "Prerecorded audio synchronized with text"
    ),
    "Appearance can be modified": _("Appearance can be modified"),
    "Appearance cannot be modified": _("Appearance cannot be modified"),
}
